version: "3.7"

services:

  # MariaDB
  mariadb:
    container_name: mariadb
    image: mariadb:10.7.4-focal
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: 'pwd123'
        MYSQL_ROOT_HOST: "%"
        # MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: 'db_user'
        MYSQL_PASSWORD: 'pass123'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes: 
        - db-data:/var/lib/mysql
    networks: 
      - proxy
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677

  # Redis
  redis:
    container_name: redis
    image: redis:latest
    volumes: 
        - redis-data:/data
    networks: 
        - proxy

networks:
  proxy:
    external: true

volumes:
  db-data:
  redis-data:
